name: Run BTC Options Bot Daily

on:
  schedule:
    - cron: '30 13 * * *'  # Runs daily at 1:30 PM UTC (1 hour before US market opens)
  workflow_dispatch:  # Optional manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run options bot
        env:
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          DELTA_INDIA_API_KEY: ${{ secrets.DELTA_INDIA_API_KEY }}
          DELTA_INDIA_API_SECRETE: ${{ secrets.DELTA_INDIA_API_SECRETE }}
        run: |
          python options.py --expiry auto --save
