name: Run BTC Options Bot Daily

on:
  schedule:
    # Runs daily at 7:30 AM EST (12:30 PM UTC)
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv pydantic pytest
          pip install pandas

      - name: Run options bot
        env:
          DELTA_INDIA_API_KEY: ${{ secrets.DELTA_INDIA_API_KEY }}
          DELTA_INDIA_API_SECRETE: ${{ secrets.DELTA_INDIA_API_SECRETE }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python options.py
